[workspace]
members = [
    "sparse-by-default-cratesio",
    "oncecell-and-oncelock-example",
    "ed25519-example",
    "deep-learning-rs", # just for deeep learning
    "llm-chain-example",
    "rust-for-rustaceans",
    "examples/*",
]
resolver = "2"
